### ISSUE TITLE
BNC male plug version 

### ISSUE THREAD

**Issue by dl1hbt** [DG1JAN/UniBalun#1]
Jan, I am a big fan of less cable whereever possible. Do you think it might be possible to change the PCB design to be able to use a BNC male plug 90 deg angle as well? I have found this one on amazon: https://amzn.eu/d/83ZCG39 but did not order any by now. Maybe it fits without the need to change the PCB design...vy73/55, Tom (DL1HBT)

**Comment by dl1hbt** [comment]
Hi Jan, I have ordered five BNC plugs for PCB installation via amazon. I expect them to arrive from China within the next two weeks. I will check the footage and give feedback on whether it works with or without the need to edit the PCB design. vy73/55, Tom

**Comment by dl1hbt** [comment]
Jan, that´s perfect...thanks for your actions taken. My address is up-to-date, I am looking forward to receiving the PCB and will reply as soon as I have received the BNC plugs from China. Thanks also for your hint oncerning the necessity for a counterpoise! vy73/55, Tom

**Comment by dl1hbt** [comment]
Jan, PCB v1.1 arrived today...thanks!

**Comment by dl1hbt** [comment]
Jan, received the BY-BNC 90 deg angle plug for PCB mountage yesterday. I will send you one sample, prbably you might want to check, if the PCB design can be modified easily and a mount point for a counterpoise can be marked on the board. vy73/55, Tom

**Comment by DG1JAN** [comment]
Hi Tom, thanks. I will have a look and will do a  "special" version that support your connector. In this case I think it makes sense to remove the posibillity for BalUn usage of the PCB (as it will be attached to radio directlý, the Dipol configuration will make no sense anyhow. 
Then I can use the "A" antenna connector for GND/Counterpoise and "B" will be for the Antenna.

**Comment by dl1hbt** [comment]
Hi Jan, yes...maybe it is clever to seperate the PCBs capability to handle Balun _and_ UnUn... 
Back from SOTA in DM/TH and DM/HE, Tom

**Comment by DG1JAN** [comment]
Thanks Tom,

part has arrived :-) The Footprint is not compatible with the SMA-connector, so I made a new Version (only 1:49) with your Part.
All Files (KiCad and  Gerber) can be found here: https://github.com/DG1JAN/AntennaPlayground/tree/main/DL1HBT_UnUn
